### ISSUE TITLE
custom option

### ISSUE THREAD

**Issue by akan091** [RDXLR/NPhisher#3]
it would be good if it had a custom web templete option 
it is a great tool

**Comment by RDXLR** [comment]
Tool is still on working tool is not completely uploaded, Soo it will be uploaded once it's is uploaded, I will close this issue

**Comment by RDXLR** [comment]
I have uploaded the maximum of sites for now, Soon i will be uploading it and as u asked custom web template is not possible for the following reasons i said before, I am closing this issue now
